CC = gcc
CFLAGS = -std=c17 -Wall -Werror -pedantic -g

# TO STUDENT: You may add to this file, but there must remain a target named
#   "HookBook" that generates an executable named the same.

HookBook :
    # TODO: You must complete the rule to compile HookBook
